site_name: Notes
site_url: https://santisbon.github.io/reference/
repo_url: https://github.com/santisbon/reference
nav:
  - Home: 'index.md'
  - Set up a new machine:
    - Install the OS: 'install-os.md'
    - Automated setup: 'automated.md'
    - Package Manager: 'package-mgmt.md'
    - Shell: 'shell.md'
    - Utilities: 'utilities.md'
    - Code Editor: 'editor.md'
    - Git: 'git.md'
    - Python: 'python.md'
    - AWS: 'aws.md'
    - MySQL: 'mysql.md'
    - Node: 'node.md'
  - Docker: 'docker.md'
  - Kubernetes: 'k8s.md'
  - Raspberry Pi: 'rpi.md'
  - MicroK8s: 'microk8s.md'
  #- Ceph: 'ceph.md'
  - MkDocs: 'mkdocs.md'
markdown_extensions:
  - toc:
      permalink: "#"
  - mdx_math
  - admonition
  - sane_lists
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences
  - pymdownx.keys
theme:
  name: material
  features:
    #- navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
extra_javascript: 
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
docs_dir: src
edit_uri: edit/main/src/
site_dir: docs
