#!/bin/zsh
./gh-md-toc $1 > temp/toc.md
cat temp/toc.md $1 > temp/toc-content.md
rm -rf temp/toc.md
pbcopy < temp/toc-content.md # "xclip -selection clipboard" on linux
echo "TOC and content saved to temp/toc-content.md and copied to clipboard"