apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
  namespace: rook-ceph-external # namespace:cluster
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  # optionally, the ceph-mgr IP address can be passed to gather metric from the prometheus exporter
  # monitoring:
  #   enabled: true
  #   externalMgrEndpoints:
  #   - ip: ip
  #     externalMgrPrometheusPort: 9283
